MODEL:
  FEATURE_DIM: 32


INPUT:
  SIZE_RAW: [1920,1200]  # Size of the original image
  SIZE_TRAIN: [720,450]  # Size of the image during training
  SIZE_TEST: [720,450]  # Size of the image during test
  NEAR_FAR_SIZE: [13.0, 37.0, 1]  # Range of distance from point cloud to cameras
#   USE_RGB: False

DATASETS:
  TRAIN: "/data/dataset/ma_1202_f"  # Path to dataset
  MASK: True  # whether to set a focus center for each camera
  CENTER: [585,1568,576,1150,546,1330,584,939]  # focus center for each real camera, [y1,x1,y2,x2,y3,x3,...]. Different for scenes
  SHIFT: 10  # Translation range in data augmentation: [-SHIFT,SHIFT]
  MAXRATION: 0.5  # Scale range in data augmentation: [1,1+MAXRATION]
  ROTATION: 0.0  # Rotation range in data augmentation: [-ROTATION,ROTATION]


SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.00002
  IMS_PER_BATCH: 3
  WARMUP_FACTOR: 0.333
  WARMUP_ITERS: 20
  WARMUP_METHOD: "linear"
  MAX_EPOCHS: 1500

TEST:
  IMS_PER_BATCH: 256

OUTPUT_DIR: "/data/training/publish_test_0402"
