

MODEL:
  FEATURE_DIM: 32


INPUT:
  SIZE_TRAIN: [256,256]
  SIZE_TEST: [256,256]
  NEAR_FAR_SIZE: [1.0, 100.0, 1]
  USE_RGB: False

DATASETS:
  TRAIN: "demo/shapenet_data"
  MASK: True
  CENTER: [400,400]
  SHIFT: 10
  MAXRATION: 0.5
  ROTATION: 0.0


SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.00002
  IMS_PER_BATCH: 3
  WARMUP_FACTOR: 0.333
  WARMUP_ITERS: 20
  WARMUP_METHOD: "linear"
  MAX_EPOCHS: 1500

TEST:
  IMS_PER_BATCH: 256

OUTPUT_DIR: "demo/shapenet_models/exp1"
